### ISSUE TITLE
🐛 connect/connect-gcp-spanner-sink Invalid instance ID

### ISSUE THREAD

**Issue by nirutgupta** [vdesabou/kafka-docker-playground#7292]
`ERROR: (gcloud.spanner.databases.delete) INVALID_ARGUMENT: Invalid GetDatabase request.- '@type': type.googleapis.com/google.rpc.BadRequest  fieldViolations:  - description: |-      Expected projects/{project ID}/instances/{instance ID}/databases/{database name}      Got: projects/connect-205118/instances/pgsemaphoresi18.0.x-latest-ubi9/databases/pgsemaphoresd18.0.x-latest-ubi9      Error: Invalid instance ID: `pgsemaphoresi18.0.x-latest-ubi9`.  Instance ID must start with a lowercase letter, be 2-64 characters long, contain only lowercase letters, numbers, or hyphens, and not end with a hyphen.     field: nameDelete instance [pgsemaphoresi18.0.x-latest-ubi9]. Are you sure?Do you want to continue (Y/n)?  ERROR: (gcloud.spanner.instances.delete) INVALID_ARGUMENT: Invalid DeleteInstance request.- '@type': type.googleapis.com/google.rpc.BadRequest  fieldViolations:  - description: |-      Expected projects/{project ID}/instances/{instance ID}      Got: projects/connect-205118/instances/pgsemaphoresi18.0.x-latest-ubi9      Error: Invalid instance ID: `pgsemaphoresi18.0.x-latest-ubi9`.  Instance ID must start with a lowercase letter, be 2-64 characters long, contain only lowercase letters, numbers, or hyphens, and not end with a hyphen.     field: name12:08:20 ℹ️ Create a Spanner Instance and DatabaseERROR: (gcloud.spanner.instances.create) INVALID_ARGUMENT: Invalid instance ID: `pgsemaphoresi18.0.x-latest-ubi9`.  Instance ID must start with a lowercase letter, be 2-64 characters long, contain only lowercase letters, numbers, or hyphens, and not end with a hyphen. 12:08:21 🔥 ####################################################12:08:21 🔥 🔥 RESULT: FAILURE for gcp-spanner-sink.sh (took: 0min 34sec - )12:08:21 🔥 ####################################################12:08:21 ℹ️`

@vdesabou  the test started to fail post few commits done today

**Comment by nirutgupta** [comment]
https://semaphore.ci.confluent.io/jobs/1f4b8772-633a-411d-ac99-0b87f546a312/summary?report_id=4ae71336-e44b-39bf-b9d2-752e234818a5&test_id=36f93568-ad07-372c-870a-84d6a40d9c4b

**Comment by vdesabou** [comment]
should be fixed by https://github.com/vdesabou/kafka-docker-playground/commit/ff95f53cc1013071643efe0e11d49daa0f320339

**Comment by nirutgupta** [comment]
```Error: Invalid instance ID: `pgsemaphoresi18.0.x`.  Instance ID must start with a lowercase letter, be 2-64 characters long, contain only lowercase letters, numbers, or hyphens, and not end with a hyphen.``` 
Still the same issue [ref](https://semaphore.ci.confluent.io/workflows/441ddf86-b720-4e73-8b16-9727f9e8f6e1/summary?report_id=4ae71336-e44b-39bf-b9d2-752e234818a5&pipeline_id=1c965e0f-899a-402b-bcd5-698784a4379e&test_id=36f93568-ad07-372c-870a-84d6a40d9c4b)

I think we need to get rid of '.' here @vdesabou

**Comment by vdesabou** [comment]
@nirutgupta I see, it should be fixed with https://github.com/vdesabou/kafka-docker-playground/commit/281ffb9aeeb0c0e300f004e21804e2566b69eee9

**Comment by nirutgupta** [comment]
it is working now, thanks https://semaphore.ci.confluent.io/jobs/d66e5aa4-4568-4ddf-b513-e1daae62c033/summary?report_id=4ae71336-e44b-39bf-b9d2-752e234818a5&suite_id=bb6af881-36fa-3751-b75e-5a14d88b4478&test_id=36f93568-ad07-372c-870a-84d6a40d9c4b
